[package]
name = "current_track"
version = "0.1.0"
authors = ["Jakub Fijałkowski <kuba@codinginfinity.me>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dbus = "0.9.7"
itertools = "0.12.1"
