misc {
    disable_hyprland_logo = true
    disable_splash_rendering = true
    force_default_wallpaper = 0
    initial_workspace_tracking = 1
}

input {
    numlock_by_default = true
    kb_layout = pl
}

cursor {
    no_warps = 1
    no_hardware_cursors = 1
}

windowrulev2 = workspace emptym,fullscreen, stayfocused, decorate 0, noanim, noborder, nodim, norounding, noshadow, class:^(sddm-greeter)$

$CURSOR_THEME=Bibata-Modern-Ice
$CURSOR_SIZE=24

exec-once = hyprctl setcursor $CURSOR_THEME $CURSOR_SIZE
env = HYPRCURSOR_THEME,$CURSOR_THEME
env = HYPRCURSOR_SIZE,$CURSOR_SIZE
