misc {
    disable_hyprland_logo = true
    disable_splash_rendering = true
    force_default_wallpaper = 0
    initial_workspace_tracking = 1
}

input {
    numlock_by_default = true
    kb_layout = pl
}

cursor {
    no_warps = 1
    no_hardware_cursors = 1
}

windowrule {
    name = sddm
    match:class = ^(sddm-greeter)$

    workspace = emptym
    fullscreen = 1
    stay_focused = 1
    no_anim = 1
    no_dim = 1
    no_shadow = 1
    decorate = 0
    border_size = 0
    rounding = 0
}

misc {
    disable_watchdog_warning = 1
}

$CURSOR_THEME=Bibata-Modern-Ice
$CURSOR_SIZE=24

exec-once = hyprctl setcursor $CURSOR_THEME $CURSOR_SIZE
env = HYPRCURSOR_THEME,$CURSOR_THEME
env = HYPRCURSOR_SIZE,$CURSOR_SIZE
