[General]
GreeterEnvironment=QT_SCREEN_SCALE_FACTORS=2,QT_FONT_DPI=192,QT_WAYLAND_SHELL_INTEGRATION=layer-shell
DisplayServer=wayland

[Wayland]
EnableHiDPI=true
CompositorCommand=Hyprland -c /opt/hyprsddm/hyprland.conf

[X11]
Enable=false
