# General
bindd = SUPER, Q, Close window, killactive,
bindd = SUPER, F, Toggle fullscreen, fullscreen, toggle
bindd = SUPER, U, Toggle floating flag, togglefloating,

bindd = SUPER, I, Toggle the split direction, togglesplit,
bindd = SUPER, G, Toggle window grouping, togglegroup
bindd = SUPER ALT, G, Move active window out of group, moveoutofgroup

binddm = SUPER, mouse:272, Move window, movewindow
binddm = SUPER, mouse:273, Resize window, resizewindow

# Applications
bindd = SUPER, SPACE, Launch apps, exec, uwsm-app -- walker
bindd = SUPER, R, Launch cmd, exec, uwsm-app -- walker --provider runner
bindd = SUPER, C, Launch cmd, exec, uwsm-app -- walker --provider clipboard

bindd = SUPER, E, Launch Nautilus, exec, uwsm-app -- nautilus
bindd = SUPER, Return, Launch Terminal, exec, uwsm-app -- xdg-terminal-exec

bindd = , PRINT, Screen screenshot, exec, hyprshot -m output --raw | satty --filename -
bindd = SHIFT, PRINT, Region screenshot, exec, hyprshot -m region --raw | satty --filename -
bindd = CTRL SHIFT, PRINT, Window screenshot, exec, hyprshot -m window -- raw | satty --filename -

# Notifications
bindd = SUPER, COMMA, Toggle notifications panel, exec, swaync-client --toggle-panel --skip-wait
bindd = SUPER ALT, COMMA, Dismiss last notification, exec, swaync-client --hide-latest --skip-wait
bindd = SUPER SHIFT, COMMA, Close all notification, exec, swaync-client --close-all --skip-wait

# Movements
bindd = SUPER, H, Move focus left, movefocus, l
bindd = SUPER, J, Move focus down, movefocus, d
bindd = SUPER, K, Move focus up, movefocus, u
bindd = SUPER, L, Move focus right, movefocus, r

bindd = SUPER SHIFT, H, Swap window left, swapwindow, l
bindd = SUPER SHIFT, J, Swap window down, swapwindow, d
bindd = SUPER SHIFT, K, Swap window up, swapwindow, u
bindd = SUPER SHIFT, L, Swap window right, swapwindow, r

bindd = SUPER, 1, Switch to workspace 1, workspace, 1
bindd = SUPER, 2, Switch to workspace 2, workspace, 2
bindd = SUPER, 3, Switch to workspace 3, workspace, 3
bindd = SUPER, 4, Switch to workspace 4, workspace, 4
bindd = SUPER, 5, Switch to workspace 5, workspace, 5
bindd = SUPER, 6, Switch to workspace 6, workspace, 6
bindd = SUPER, 7, Switch to workspace 7, workspace, 7
bindd = SUPER, 8, Switch to workspace 8, workspace, 8
bindd = SUPER, 9, Switch to workspace 9, workspace, 9
bindd = SUPER, 0, Switch to workspace 10, workspace, 10

bindd = SUPER SHIFT, 1, Move to workspace 1, movetoworkspace, 1
bindd = SUPER SHIFT, 2, Move to workspace 2, movetoworkspace, 2
bindd = SUPER SHIFT, 3, Move to workspace 3, movetoworkspace, 3
bindd = SUPER SHIFT, 4, Move to workspace 4, movetoworkspace, 4
bindd = SUPER SHIFT, 5, Move to workspace 5, movetoworkspace, 5
bindd = SUPER SHIFT, 6, Move to workspace 6, movetoworkspace, 6
bindd = SUPER SHIFT, 7, Move to workspace 7, movetoworkspace, 7
bindd = SUPER SHIFT, 8, Move to workspace 8, movetoworkspace, 8
bindd = SUPER SHIFT, 9, Move to workspace 9, movetoworkspace, 9
bindd = SUPER SHIFT, 0, Move to workspace 10, movetoworkspace, 10

bindd = SUPER, TAB, Next window in group, changegroupactive, f
bindd = SUPER SHIFT, TAB, Prev window in group, changegroupactive, b

## Laptop multimedia keys for volume and LCD brightness
bindel = ,XF86AudioRaiseVolume, exec, wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+
bindel = ,XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindel = ,XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindel = ,XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
bindel = ,XF86MonBrightnessUp, exec, brightnessctl -e4 -n2 set 5%+
bindel = ,XF86MonBrightnessDown, exec, brightnessctl -e4 -n2 set 5%-

## Requires playerctl
bindl = , XF86AudioNext, exec, playerctl next
bindl = , XF86AudioPause, exec, playerctl play-pause
bindl = , XF86AudioPlay, exec, playerctl play-pause
bindl = , XF86AudioPrev, exec, playerctl previous
