hl.env("GDK_SCALE", "1.5")

hl.monitor({ output = "DP-1", mode = "preferred", position = "auto", scale = 1.5 })
hl.monitor({ output = "DP-4", mode = "preferred", position = "auto-right", scale = 1.5 })
hl.monitor({ output = "", mode = "preferred", position = "auto", scale = 1.5 })

hl.workspace_rule({ workspace = "1", monitor = "DP-1" })
hl.workspace_rule({ workspace = "2", monitor = "DP-1" })
hl.workspace_rule({ workspace = "3", monitor = "DP-1" })
hl.workspace_rule({ workspace = "4", monitor = "DP-1" })
hl.workspace_rule({ workspace = "5", monitor = "DP-1" })
hl.workspace_rule({ workspace = "6", monitor = "DP-4" })
hl.workspace_rule({ workspace = "7", monitor = "DP-4" })
hl.workspace_rule({ workspace = "8", monitor = "DP-4" })
hl.workspace_rule({ workspace = "9", monitor = "DP-4" })
hl.workspace_rule({ workspace = "10", monitor = "DP-4" })
