# Tagging for future use

## Browser
windowrule = match:initial_class ((google-)?[cC]hrom(e|ium)|[bB]rave-browser|Microsoft-edge), tag +chromium-based-browser
windowrule = match:tag chromium-based-browser, match:initial_title ^(Meet.+)$, match:float 1, tag +pip
windowrule = match:initial_title ^(meet.google.com is sharing a window.), tag +share

# Configs

## Ignore maximize requests from apps. You'll probably like this.
windowrule {
    name = suppress-maximize
    match:class = .*

    suppress_event = maximize
}

# Fix some dragging issues with XWayland
windowrule {
    name = fix-xwayland-drag
    match:class = ^$
    match:title = ^$
    match:xwayland = 1
    match:float = 1
    match:fullscreen = 0
    match:pin = 0

    no_focus = true
}

# No-border when single window
workspace = w[tv1], gapsout:0, gapsin:0
workspace = f[1], gapsout:0, gapsin:0

windowrule {
    name = no-border-single-tiled
    match:float = 0
    match:workspace = w[tv1]

    border_size = 0
    rounding = 0
}

windowrule {
    name = no-border-single-fullscreen

    match:float = 0
    match:workspace = f[1]

    border_size = 0
    rounding = 0
}

# Picture-in-picture
windowrule {
    name = pip

    match:tag = pip

    # These don't work, Chrome does something strange when opening the PiP window :(
    float = true
    pin = true
    opaque = true

    border_size = 0
    no_dim = true
    no_follow_mouse = true
    no_shadow = true
}

# Share indicators
windowrule {
    name = share-indicator
    match:tag = share

    move = (monitor_w-window_w) (monitor_h-window_h-10)

    border_size = 0
    no_follow_mouse = true
    no_shadow = true
}

# App-specific

## Screensaver
windowrule {
    name = screensaver
    match:class = Screensaver

    fullscreen = true
}

## Calculator
windowrule {
    name = calculator
    match:class = org.gnome.Calculator

    float = true
}

## File dialog
windowrule {
    name = file-dialog
    match:class = xdg-desktop-portal-gtk
    match:title = ^(Open.*Files?|Open [F|f]older.*|Save.*Files?|Save.*As|Save|All Files|.*wants to [open|save].*|[C|c]hoose.*)

    float = true
    center = true
    size = 1024 768
}

## Satty
windowrule {
    name = satty
    match:initial_class = com.gabm.satty

    float = true
    center = true
    size = 1024 768
    pin = true
}


## Slack
windowrule {
    name = slack-screenshare
    match:class = ^ss:^([sS]lack)$

    no_screen_share = true
}

windowrule {
    name = slack
    match:initial_class = ^([sS]lack)$

    workspace = 10
    no_initial_focus = true
}

## Spotify
windowrule {
    name = spotify
    match:initial_class = ^([sS]potify)$

    workspace = 9
    no_initial_focus = true
}

## Kingdom Battle
windowrule {
    name = kingdom-battle
    match:initial_class = ^(kingdom-battle)$

    workspace = 8
    no_initial_focus = true
}

## 1Password
windowrule {
    name = 1password
    match:initial_class = 1password

    size = (monitor_w*0.8) (monitor_h*0.9)

    float = true
    center = true
    pin = true
}

## GeForceNow
windowrule {
    name = geforcenow
    match:title = ^(.+GeForce NOW.+)$

    immediate = true
    tag = geforce
}
