# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppressevent maximize, class:.*

# Fix some dragging issues with XWayland
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

# Floating windows
windowrule = tag +floating-window, class:(org.gnome.NautilusPreviewer|com.gabm.satty)
windowrule = tag +floating-window, class:(xdg-desktop-portal-gtk|sublime_text|DesktopEditors|org.gnome.Nautilus), title:^(Open.*Files?|Open [F|f]older.*|Save.*Files?|Save.*As|Save|All Files|.*wants to [open|save].*|[C|c]hoose.*)

windowrule = float, tag:floating-window
windowrule = center, tag:floating-window
windowrule = size 875 600, tag:floating-window
windowrule = float, class:org.gnome.Calculator

# Fullscreen screensaver
windowrule = fullscreen, class:Screensaver

# Browsers
windowrule = tag +chromium-based-browser, class:((google-)?[cC]hrom(e|ium)|[bB]rave-browser|Microsoft-edge|Vivaldi-stable|helium)
windowrule = tile, tag:chromium-based-browser

# No-border when single widnow
workspace = w[tv1], gapsout:0, gapsin:0
workspace = f[1], gapsout:0, gapsin:0
windowrule = bordersize 0, floating:0, onworkspace:w[tv1]
windowrule = rounding 0, floating:0, onworkspace:w[tv1]
windowrule = bordersize 0, floating:0, onworkspace:f[1]
windowrule = rounding 0, floating:0, onworkspace:f[1]

# Picture-in-picture
windowrule = float, tag:pip
windowrule = pin, tag:pip
windowrule = size 600 338, tag:pip
windowrule = noborder, tag:pip
windowrule = move 100%-w-40 4%, tag:pip

# Share indicators
windowrule = noborder, tag:share
windowrule = move 50%-w-50 100%-w-5, tag:share

# App-specific

## Slack
windowrule = noscreenshare, class:^ss:^(Slack)$
windowrule = workspace 10, initialClass:^(Slack)$
windowrule = noinitialfocus, initialClass:^(Slack)$

## Spotify
windowrule = workspace 9, initialClass:^(spotify)$
windowrule = noinitialfocus, initialClass:^(spotify)$

## Browsers
windowrule = tag +pip, tag:chromium-based-browser, title:^(Meet.+), floating:1
windowrule = tag +share, title:^(meet.google.com is sharing a window.)
