#!/bin/bash

max_brightness=$(cat /sys/class/backlight/intel_backlight/max_brightness)
brightness=$(cat /sys/class/backlight/intel_backlight/brightness)

if [[ "$1" == "down" ]]; then
    let brightness=$brightness-100
    if (($brightness < 1)); then
        let brightness=1
    fi
elif [[ "$1" == "up" ]]; then
    let brightness=$brightness+100
    if (($brightness > $max_brightness)); then
        let brightness=$max_brightness
    fi
fi

echo $brightness > /sys/class/backlight/intel_backlight/brightness
