#!/bin/sh

trap 'print_updates' USR1

updates="0"
print_updates() {
    if [ "$updates" != "0" ]; then
        echo $updates
    else
        echo ""
    fi
}

while true; do
    updates=$(yay -Quq | wc -l)
    print_updates

    sleep 1200 &
    wait $!
done

