#!/bin/sh

has_main=$(xrandr | grep "^$DISPLAY_CONFIG_MAIN connected" 2>/dev/null || true)

if [[ $has_main != "" ]]; then
    if [[ "$DISPLAY_MODE" == "main-on-top" ]]; then
        xrandr --output $DISPLAY_CONFIG_MAIN --primary --auto \
          --above $DISPLAY_CONFIG_ALTERNATIVE
        i3-msg restart
    else
        echo "Unknown mode: $DEFAULT_MODE"
        exit 1
    fi
else
    xrandr --output $DISPLAY_CONFIG_ALTERNATIVE --primary
    xrandr --auto
fi
