#!/bin/env bash

if [[ "$(rfkill --json | jq -Mr '.rfkilldevices[] | select(.type == "bluetooth").hard')" == "blocked" ]]; then
    rfkill unblock bluetooth
fi
if bluetoothctl show | grep -q 'Powered: no'; then
    bluetoothctl power on
fi

for i in $(seq 1 10); do
    echo "Trying $i/10"
    bluetoothctl connect $HEADPHONES_MAC
    sink=$(pactl list short sinks | grep 'bluez' | awk -F' ' '{print $1}')
    if [[ "$sink" != "" ]]; then
        break
    fi
    sleep 1
done

sink=$(pactl list short sinks | grep 'bluez' | awk -F' ' '{print $1}')
if [ "$sink" = "" ]; then
  notify-send -u critical -a Headphones Headphones 'Connection failed'
fi
