#!/bin/env bash

if [[ "$(rfkill --json | jq -Mr '.""[] | select(.type == "bluetooth").hard')" == "blocked" ]]; then
    rfkill unblock bluetooth
fi
if bluetoothctl show | grep -q 'Powered: no'; then
    bluetoothctl power on
fi

bluetoothctl connect $HEADPHONES_MAC

sink=$(pactl list short sinks | grep 'bluez' | awk -F' ' '{print $1}')
if [ "$sink" = "" ]; then
  notify-send -u critical -a Headphones Headphones 'Connection failed'
fi
