#!/bin/zsh

__current-spotify-track() {
    local metadata=$(dbus-send \
        --print-reply \
        --session \
        --dest=org.mpris.MediaPlayer2.spotify \
        /org/mpris/MediaPlayer2 \
        org.freedesktop.DBus.Properties.GetAll \
        string:org.mpris.MediaPlayer2.Player 2>/dev/null)
    local title=$(echo $metadata | sed -n '/xesam:title/{n;p}' | \
        sed -E 's/.+"(.+)"/\1/')
    local artist=$(echo $metadata | sed -n '/xesam:artist/{n;n;p}' | \
        sed -E 's/.+"(.+)"/\1/')
    echo "$artist - $title"
}

if [[ `systemctl --user is-active mpd` == 'active' ]]; then
    mpc current
    while [[ $? == 0 ]]; do
        mpc current --wait 2>/dev/null
    done
    echo ""
    exit 0
elif pidof -x spotify > /dev/null; then
    __current-spotify-track
    dbus-monitor --session "sender='org.mpris.MediaPlayer2.spotify'" --profile | \
        while read -r ln; do
            if pidof -x spotify > /dev/null; then
                if [[ "$ln" != mr* ]]; then
                    __current-spotify-track
                fi
            else
                echo ""
                exit 0
            fi
        done
fi
echo ""
