#!/usr/bin/env zsh

current_context=$(kubectl config current-context)
token_name=$1
context=${2:-$current_context}

cluster=$(kubectl config view -o jsonpath='{.contexts[?(@.name == "'$context'")].context.cluster}')
server=$(kubectl config view -o jsonpath='{.clusters[?(@.name == "'$cluster'")].cluster.server}')
name=default-token-sg96k

ca=$(kubectl get secret/$token_name -o jsonpath='{.data.ca\.crt}')
token=$(kubectl get secret/$token_name -o jsonpath='{.data.token}' | base64 --decode)
namespace=$(kubectl get secret/$token_name -o jsonpath='{.data.namespace}' | base64 --decode)

echo "apiVersion: v1
kind: Config
clusters:
- name: default-cluster
  cluster:
    certificate-authority-data: ${ca}
    server: ${server}
contexts:
- name: default-context
  context:
    cluster: default-cluster
    namespace: default
    user: default-user
current-context: default-context
users:
- name: default-user
  user:
    token: ${token}"
