#!/usr/bin/env zsh
function start_player() {
  systemctl --user start mopidy
}

function stop_player() {
  systemctl --user stop mopidy
}

function player_running() {
  systemctl --user is-active mopidy
}

function run_control() {
  $TERMINAL --title 'Music' --class 'ncmpcpp-player' -e 'ncmpcpp'
}

if [[ "$1" == "stop" ]]; then
  stop_player
elif [[ "$1" == "iris" ]]; then
  start_player
  xdg-open "http://localhost:6680/iris/"
elif [[ "$1" == "bg" ]]; then
  start_player
elif [[ "$(player_running)" == "active" ]]; then
  run_control
else
  start_player
  run_control
  stop_player
fi

