#!/bin/sh

device="VEN_04F3:00 04F3:311C Touchpad"
is_disabled=$(xinput list-props "$device" | grep -E '^.+Device Enabled.+0$')

if [ "$is_disabled" = "" ]; then
    xinput disable "$device"
else
    xinput enable "$device"
fi
