#!/usr/bin/env bash

device="DLL07BE:01 06CB:7A13 Touchpad"
is_disabled=$(xinput list-props "$device" | grep -E '^.+Device Enabled.+0$')

if [[ "$is_disabled" == "" ]]; then
    xinput disable "$device"
else
    xinput enable "$device"
fi
