#!/bin/zsh

OPTIONS_FLAG='--options'
EXCLUDE_FLAG='--exclude'

PARAMS='-c --ignore-close-implementation -x'

for x in $@; do
    if [ ${x:0:${#OPTIONS_FLAG}} != $OPTIONS_FLAG ] &&
       [ ${x:0:${#EXCLUDE_FLAG}} != $EXCLUDE_FLAG ]; then
        PARAMS="$PARAMS $x"
    fi
done

eval hasktags -c --ignore-close-implementation -x $PARAMS
